
function refUser(){const s=JSON.parse(localStorage.getItem("cashHubNgSession")||"null");if(!s)return null;return JSON.parse(localStorage.getItem("cashHubNgUsers")||"[]").find(u=>u.id===s.id)}
function saveRefUser(u){const users=JSON.parse(localStorage.getItem("cashHubNgUsers")||"[]");const i=users.findIndex(x=>x.id===u.id);if(i>=0)users[i]=u;localStorage.setItem("cashHubNgUsers",JSON.stringify(users))}
function refCode(u){return "CH"+String(u.id).replace(/[^a-z0-9]/gi,"").slice(-6).toUpperCase()}
function refLink(u){return location.origin+location.pathname.replace(/[^/]*$/,"")+"signup.html?ref="+refCode(u)}
function renderReferral(){const u=refUser();if(!u){location.href="login.html";return}const code=refCode(u),link=refLink(u);document.getElementById("ref-code").textContent=code;document.getElementById("ref-link").value=link;document.getElementById("ref-count").textContent=(u.referrals||[]).length;document.getElementById("ref-earnings").textContent="$"+Number(u.referralEarnings||0).toFixed(2);const list=document.getElementById("ref-list"),refs=u.referrals||[];list.innerHTML=refs.length?refs.map(r=>`<div class="transaction"><div><strong>${r.name}</strong><small>Joined ${new Date(r.date).toLocaleDateString()}</small></div><span class="status pending">Joined</span></div>`).join(""):`<div class="empty-state"><span>👥</span><h3>No referrals yet</h3><p>Share your referral link to start inviting friends.</p></div>`}
function copyRef(){const input=document.getElementById("ref-link");if(navigator.clipboard)navigator.clipboard.writeText(input.value);else{input.select();document.execCommand("copy")}document.getElementById("ref-copy-status").textContent="Referral link copied!"}
function shareRef(){const u=refUser(),data={title:"Join Cash Hub NG",text:"Join me on Cash Hub NG and explore available earning opportunities.",url:refLink(u)};if(navigator.share)navigator.share(data);else copyRef()}
function setupReferralSignup(){const code=new URLSearchParams(location.search).get("ref");if(!code)return;const note=document.getElementById("referral-note");if(note)note.textContent="You were invited by referral code "+code+".";sessionStorage.setItem("cashHubReferralCode",code)}
function attachReferralToNewUser(user){const code=sessionStorage.getItem("cashHubReferralCode");if(!code)return;const users=JSON.parse(localStorage.getItem("cashHubNgUsers")||"[]"),inviter=users.find(u=>("CH"+String(u.id).replace(/[^a-z0-9]/gi,"").slice(-6).toUpperCase())===code);if(inviter&&inviter.id!==user.id){inviter.referrals=inviter.referrals||[];inviter.referrals.push({name:user.name,email:user.email,date:new Date().toISOString()});inviter.referralEarnings=Number(inviter.referralEarnings||0)+1;inviter.balance=Number(inviter.balance||0)+1;inviter.earnings=Number(inviter.earnings||0)+1;inviter.transactions=inviter.transactions||[];inviter.transactions.unshift({id:Date.now().toString(),type:"referral",title:"Referral bonus",amount:1,date:new Date().toISOString()});users[users.findIndex(u=>u.id===inviter.id)]=inviter;localStorage.setItem("cashHubNgUsers",JSON.stringify(users))}sessionStorage.removeItem("cashHubReferralCode")}
